### PR TITLE
Update MCM to v0.40.0

### PR DESCRIPTION
**Pull request by kon-angelo**
**What this PR does / why we need it**:

Update MCM dependency to latest version.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
Update machine-controller-manager to v0.40.0
```

### CODE REVIEW

**Review by AxiomSamarth — APPROVED** [review]
/lgtm

**Comment by AxiomSamarth** [comment]
Very soon, this vendoring of latest MCM versions is going to be automated on all providers. Take a look at this [PR](https://github.com/gardener/machine-controller-manager-provider-aws/pull/41) on AWS.

**Review by prashanth26 — APPROVED** [review]
/lgtm

Keep in mind that while merging with extension provider we would need to update the RBACs [like this](https://github.com/gardener/gardener-extension-provider-gcp/pull/304)

**Comment by kon-angelo** [comment]
@prashanth26 Thank you for the heads-up :)

**Pull request merged**
