### PR TITLE
Update MCM(v0.42.0) and gardener(v1.35.1) dependencies

### PR DESCRIPTION
**Pull request by kon-angelo**
**What this PR does / why we need it**:

Update gardener and mcm dependencies. 
**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user

```

### CODE REVIEW

**Review by dkistner — APPROVED** [review]
/lgtm
/invite @AxiomSamarth, @himanshu-kun

**Comment by kon-angelo** [comment]
tldr; for the force pushes: git treats file as case insensitive and one of the dependencies renames its pacakge from camelcase to lowercase. It requited a bit of extra magic (aka explicit `git mv`) operations to make git aware of the name change.

**Comment by AxiomSamarth** [comment]
> tldr; for the force pushes: git treats file as case insensitive and one of the dependencies renames its pacakge from camelcase to lowercase. It requited a bit of extra magic (aka explicit `git mv`) operations to make git aware of the name change.

Was this related to the openAPI v2 packages? Yes, I think that issue is something specific to MacOS.

**Review by AxiomSamarth — APPROVED** [review]
/lgtm

**Review by himanshu-kun — APPROVED** [review]

**Pull request merged**
