### PR TITLE
Update go version used to v1.18

### PR DESCRIPTION
**Pull request by kon-angelo**
**What this PR does / why we need it**:

Update go version used to v1.18

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
Update Go version to `v1.18`
```

### CODE REVIEW

**Review by himanshu-kun — APPROVED** [review]
/lgtm
The verify step is failing though

**Comment by kon-angelo** [comment]
Yes the pipeline had to be updated and also update the linter because of a bug marking used variables as unused.

**Pull request merged**
