### PR TITLE
Change base image to distroless

### PR DESCRIPTION
**Pull request by kon-angelo**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement user
Use distroless base image
```

### CODE REVIEW

**Comment by kon-angelo** [comment]
@himanshu-kun PTAL :)

**Review by himanshu-kun — COMMENTED** [review]
why not use `gcr.io/distroless/base:latest` ?

**Comment by kon-angelo** [comment]
I am not a fan of using `latest`, since these are not really reproducable builds. As for the choice of base image, I used this as reference https://github.com/gardener/gardener-extension-provider-gcp/pull/456 since we already had updated our base images in the other repos and used the same here.

**Comment by kon-angelo** [comment]
Diving a bit into the differences between them,  based on https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md, the `static` variants are more minimal than `base` and we definitely don't need the glibc fluff.

**Comment by himanshu-kun** [comment]
> Diving a bit into the differences between them, based on https://github.com/GoogleContainerTools/distroless/blob/main/base/README.md, the static variants are more minimal than base and we definitely don't need the glibc fluff.

Okay, thanks for pointing out the differences.

**Review by himanshu-kun — APPROVED** [review]
/lgtm
Do you suggest to do the same for other providers also?

**Comment by kon-angelo** [comment]
@himanshu-kun yes, I think we should go distroless for all our images if possible.

**Pull request merged**
